# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoveTravel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoveTravel
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'SDWebImage', '~> 4.0.0'

end
